import {readFileSync,writeFileSync,existsSync,unlinkSync} from 'node:fs';
const pages=JSON.parse(readFileSync(new URL('../src/app/seo/pages.json',import.meta.url),'utf8'));
const raw=process.env.SITE_URL || process.env.URL || 'https://guiarapidodnd.netlify.app';
let origin='';
if(raw){const url=new URL(raw);if(!['https:','http:'].includes(url.protocol)||url.username||url.password||url.pathname!=='/'||url.search||url.hash)throw new Error('SITE_URL deve ser a origem pública do site, sem caminho, parâmetros ou credenciais.');origin=url.origin;}
writeFileSync(new URL('../src/app/seo/site-config.ts',import.meta.url),`// Generated by scripts/generate-seo.mjs.\nexport const SITE_URL = ${JSON.stringify(origin)};\n`);
const sitemap=new URL('../public/sitemap.xml',import.meta.url);
const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
if(origin)writeFileSync(sitemap,`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${pages.filter(p=>!p.noindex).map(p=>`  <url><loc>${escape(origin+'/'+p.path)}</loc></url>`).join('\n')}\n</urlset>\n`);
else {if(existsSync(sitemap))unlinkSync(sitemap);console.warn('URL pública ausente: sitemap e canonical serão gerados quando SITE_URL ou a variável URL da Netlify estiver disponível.');}
const preview=['deploy-preview','branch-deploy'].includes(process.env.CONTEXT);
writeFileSync(new URL('../public/robots.txt',import.meta.url),preview?'User-agent: *\nDisallow: /\n':`User-agent: *\nAllow: /\n${origin?'\nSitemap: '+origin+'/sitemap.xml\n':''}`);
writeFileSync(new URL('../public/_headers',import.meta.url),preview?'/*\n  X-Robots-Tag: noindex, nofollow\n':'/assets/art/*\n  X-Robots-Tag: noindex\n/data/*\n  X-Robots-Tag: noindex\n/personagens/*\n  X-Robots-Tag: noindex, follow\n/busca\n  X-Robots-Tag: noindex, follow\n/monstros\n  X-Robots-Tag: noindex, follow\n');
