"""Measure transparent padding for display; original portrait files remain unchanged."""
import json
from pathlib import Path
from PIL import Image

root = Path(__file__).resolve().parents[1]
frames = {}
for prefix in ('papermage-', 'printableheroes-'):
    for path in sorted((root / 'public/assets/art').glob(prefix + '*.webp')):
        with Image.open(path) as image:
            width, height = image.size
            bounds = image.convert('RGBA').getchannel('A').getbbox()
        if not bounds:
            continue
        left, top, right, bottom = bounds
        padding = 10
        edges = (max(0, top-padding)/height, max(0, width-right-padding)/width,
                 max(0, height-bottom-padding)/height, max(0, left-padding)/width)
        frames[path.stem] = 'inset(' + ' '.join(f'{n*100:.2f}%' for n in edges) + ')'
(root / 'src/app/utils/portrait-frames.ts').write_text('// Generated by scripts/portrait-framing.py.\nexport const PORTRAIT_FRAMES: Record<string,string> = ' + json.dumps(frames, indent=2) + ';\n', encoding='utf-8')
print(f'{len(frames)} portrait frames measured')
