// Generated by scripts/prepare-papermage.py.
import type { CharacterPortrait } from './portrait-catalog';

export const PAPERMAGE_PORTRAITS: CharacterPortrait[] = [
  {
    "name": "Maga aasimar",
    "origin": "aasimar",
    "styles": [
      "mago",
      "feiticeiro"
    ],
    "appearance": "feminina",
    "id": "papermage-aasimar-wizard"
  },
  {
    "name": "Guerreira gnoma",
    "origin": "gnomo",
    "styles": [
      "guerreiro",
      "paladino"
    ],
    "appearance": "feminina",
    "id": "papermage-gnome-fighter"
  },
  {
    "name": "Guerreira elfa",
    "origin": "elfo",
    "styles": [
      "guerreiro",
      "paladino"
    ],
    "appearance": "feminina",
    "id": "papermage-elf-fighter"
  },
  {
    "name": "Monja pequenina",
    "origin": "halfling",
    "styles": [
      "monge"
    ],
    "appearance": "feminina",
    "id": "papermage-halfling-monk"
  },
  {
    "name": "Ladina draconata",
    "origin": "draconato",
    "styles": [
      "ladino",
      "guardiao"
    ],
    "appearance": "feminina",
    "id": "papermage-dragonborn-rogue"
  },
  {
    "name": "Clériga orc",
    "origin": "orc",
    "styles": [
      "clerigo",
      "paladino"
    ],
    "appearance": "feminina",
    "id": "papermage-orc-cleric"
  },
  {
    "name": "Bardo gnomo",
    "origin": "gnomo",
    "styles": [
      "bardo"
    ],
    "appearance": "masculina",
    "id": "papermage-gnome-bard"
  },
  {
    "name": "Druida gnomo",
    "origin": "gnomo",
    "styles": [
      "druida"
    ],
    "appearance": "masculina",
    "id": "papermage-gnome-druid"
  },
  {
    "name": "Barda aasimar",
    "origin": "aasimar",
    "styles": [
      "bardo"
    ],
    "appearance": "feminina",
    "id": "papermage-aasimar-bard"
  },
  {
    "name": "Paladina meio-elfa",
    "origin": "elfo",
    "styles": [
      "paladino",
      "guerreiro"
    ],
    "appearance": "feminina",
    "id": "papermage-half-elf-paladin"
  },
  {
    "name": "Paladino elfo",
    "origin": "elfo",
    "styles": [
      "paladino",
      "guerreiro"
    ],
    "appearance": "masculina",
    "id": "papermage-elf-paladin"
  },
  {
    "name": "Guardiã elfa",
    "origin": "elfo",
    "styles": [
      "guardiao"
    ],
    "appearance": "feminina",
    "id": "papermage-elf-ranger"
  },
  {
    "name": "Paladino anão",
    "origin": "anao",
    "styles": [
      "paladino",
      "guerreiro"
    ],
    "appearance": "masculina",
    "id": "papermage-dwarf-paladin"
  },
  {
    "name": "Barda elfa",
    "origin": "elfo",
    "styles": [
      "bardo"
    ],
    "appearance": "feminina",
    "id": "papermage-elf-bard"
  },
  {
    "name": "Mago elfo",
    "origin": "elfo",
    "styles": [
      "mago",
      "feiticeiro"
    ],
    "appearance": "masculina",
    "id": "papermage-elf-wizard"
  },
  {
    "name": "Barda tiferina",
    "origin": "tiefling",
    "styles": [
      "bardo"
    ],
    "appearance": "feminina",
    "id": "papermage-tiefling-bard"
  },
  {
    "name": "Bruxo tiferino",
    "origin": "tiefling",
    "styles": [
      "bruxo",
      "feiticeiro"
    ],
    "appearance": "masculina",
    "id": "papermage-tiefling-warlock"
  }
];
