// Generated by scripts/catalog-printableheroes.py.
import type { CharacterPortrait } from './portrait-catalog';

export const PRINTABLEHEROES_PORTRAITS: CharacterPortrait[] = [
  {
    "id": "printableheroes-mini-1081-0-0-standee-1-image-1",
    "name": "Ladina anã",
    "origin": "anao",
    "appearance": "feminina",
    "styles": [
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-1105-0-0-standee-1-image-1",
    "name": "Guardião pequenino",
    "origin": "halfling",
    "appearance": "masculina",
    "styles": [
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-1105-0-0-standee-1-image-2",
    "name": "Guardião pequenino · 2",
    "origin": "halfling",
    "appearance": "masculina",
    "styles": [
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-1119-0-0-standee-1-image-1",
    "name": "Cultista humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bruxo",
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-mini-1119-0-0-standee-1-image-2",
    "name": "Cultista humano · 2",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bruxo",
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-mini-1119-0-0-standee-1-image-3",
    "name": "Cultista humano · 3",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bruxo",
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-mini-1119-0-0-standee-1-image-4",
    "name": "Cultista humano · 4",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bruxo",
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-mini-1119-0-0-standee-1-image-5",
    "name": "Cultista humano · 5",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bruxo",
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-mini-1125-0-0-standee-2-image-1",
    "name": "Aventureira anã",
    "origin": "anao",
    "appearance": "feminina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-1125-0-0-standee-2-image-2",
    "name": "Aventureira anã · 2",
    "origin": "anao",
    "appearance": "feminina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-113-0-0-standee-1-image-1",
    "name": "Guardião elfo",
    "origin": "elfo",
    "appearance": "masculina",
    "styles": [
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-113-0-0-standee-1-image-2",
    "name": "Guardião elfo · 2",
    "origin": "elfo",
    "appearance": "masculina",
    "styles": [
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-1131-0-0-standee-1-image-1",
    "name": "Maga draconata",
    "origin": "draconato",
    "appearance": "feminina",
    "styles": [
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-1131-0-0-standee-1-image-2",
    "name": "Maga draconata · 2",
    "origin": "draconato",
    "appearance": "feminina",
    "styles": [
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-1132-0-0-standee-1-image-1",
    "name": "Aventureira draconata",
    "origin": "draconato",
    "appearance": "feminina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-1132-0-0-standee-1-image-2",
    "name": "Aventureira draconata · 2",
    "origin": "draconato",
    "appearance": "feminina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-114-0-0-standee-1-image-1",
    "name": "Guardião elfo · 3",
    "origin": "elfo",
    "appearance": "masculina",
    "styles": [
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-114-0-0-standee-1-image-2",
    "name": "Guardião elfo · 4",
    "origin": "elfo",
    "appearance": "masculina",
    "styles": [
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-1147-0-0-standee-1-image-1",
    "name": "Aventureiro elfo",
    "origin": "elfo",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-1147-0-0-standee-1-image-2",
    "name": "Aventureiro elfo · 2",
    "origin": "elfo",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-115-0-0-standee-1-image-1",
    "name": "Monge elfo",
    "origin": "elfo",
    "appearance": "masculina",
    "styles": [
      "monge"
    ]
  },
  {
    "id": "printableheroes-mini-115-0-0-standee-1-image-2",
    "name": "Monge elfo · 2",
    "origin": "elfo",
    "appearance": "masculina",
    "styles": [
      "monge"
    ]
  },
  {
    "id": "printableheroes-mini-1150-0-0-standee-1-image-1",
    "name": "Aventureiro elfo · 3",
    "origin": "elfo",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-1150-0-0-standee-1-image-2",
    "name": "Aventureiro elfo · 4",
    "origin": "elfo",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-1159-0-0-standee-1-image-1",
    "name": "Guerreiro humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-1159-0-0-standee-1-image-2",
    "name": "Guerreiro humano · 2",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-116-0-0-standee-1-image-1",
    "name": "Monge elfo · 3",
    "origin": "elfo",
    "appearance": "masculina",
    "styles": [
      "monge"
    ]
  },
  {
    "id": "printableheroes-mini-116-0-0-standee-1-image-2",
    "name": "Monge elfo · 4",
    "origin": "elfo",
    "appearance": "masculina",
    "styles": [
      "monge"
    ]
  },
  {
    "id": "printableheroes-mini-1160-0-0-standee-1-image-1",
    "name": "Mago tiferino",
    "origin": "tiefling",
    "appearance": "masculina",
    "styles": [
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-117-0-0-standee-1-image-1",
    "name": "Druida anã",
    "origin": "anao",
    "appearance": "feminina",
    "styles": [
      "druida"
    ]
  },
  {
    "id": "printableheroes-mini-117-0-0-standee-1-image-2",
    "name": "Druida anã · 2",
    "origin": "anao",
    "appearance": "feminina",
    "styles": [
      "druida"
    ]
  },
  {
    "id": "printableheroes-mini-120-0-0-standee-1-image-1",
    "name": "Druida elfo",
    "origin": "elfo",
    "appearance": "masculina",
    "styles": [
      "druida"
    ]
  },
  {
    "id": "printableheroes-mini-120-0-0-standee-1-image-2",
    "name": "Druida elfo · 2",
    "origin": "elfo",
    "appearance": "masculina",
    "styles": [
      "druida"
    ]
  },
  {
    "id": "printableheroes-mini-121-0-0-standee-1-image-1",
    "name": "Druida elfa",
    "origin": "elfo",
    "appearance": "feminina",
    "styles": [
      "druida"
    ]
  },
  {
    "id": "printableheroes-mini-125-0-0-gnome-cleric-0101",
    "name": "Clériga gnoma",
    "origin": "gnomo",
    "appearance": "feminina",
    "styles": [
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-mini-125-0-0-gnome-cleric-0102",
    "name": "Clériga gnoma · 2",
    "origin": "gnomo",
    "appearance": "feminina",
    "styles": [
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-mini-127-0-0-gnome-alchemist-0101",
    "name": "Alquimista gnomo",
    "origin": "gnomo",
    "appearance": "masculina",
    "styles": [
      "mago",
      "druida"
    ]
  },
  {
    "id": "printableheroes-mini-127-0-0-gnome-alchemist-0102",
    "name": "Alquimista gnomo · 2",
    "origin": "gnomo",
    "appearance": "masculina",
    "styles": [
      "mago",
      "druida"
    ]
  },
  {
    "id": "printableheroes-mini-149-0-0-orc_01",
    "name": "Guerreiro orc",
    "origin": "orc",
    "appearance": "masculina",
    "styles": [
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-15-0-0-tiefling_warlock_01_01",
    "name": "Bruxo tiferino",
    "origin": "tiefling",
    "appearance": "masculina",
    "styles": [
      "bruxo"
    ]
  },
  {
    "id": "printableheroes-mini-150-0-0-orc_01",
    "name": "Aventureiro orc",
    "origin": "orc",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-160-0-0-standee-1-image-1",
    "name": "Maga anã",
    "origin": "anao",
    "appearance": "feminina",
    "styles": [
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-160-0-0-standee-1-image-2",
    "name": "Maga anã · 2",
    "origin": "anao",
    "appearance": "feminina",
    "styles": [
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-168-0-0-elf-ranger-03-01",
    "name": "Guardiã elfa",
    "origin": "elfo",
    "appearance": "feminina",
    "styles": [
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-168-0-0-elf-ranger-03-02",
    "name": "Guardiã elfa · 2",
    "origin": "elfo",
    "appearance": "feminina",
    "styles": [
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-191-0-0-bandit---0301-",
    "name": "Bandido humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "ladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-191-0-0-bandit---0302",
    "name": "Bandido humano · 2",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "ladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-192-0-0-bandit---0301-",
    "name": "Bandido humano · 3",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "ladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-192-0-0-bandit---0302",
    "name": "Bandido humano · 4",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "ladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-194-0-0-half-orc---brawler---0101",
    "name": "Lutadora orc",
    "origin": "orc",
    "appearance": "feminina",
    "styles": [
      "monge",
      "barbaro",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-195-0-0-standee-1-image-1",
    "name": "Taverneiro humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-195-0-0-standee-1-image-2",
    "name": "Taverneiro humano · 2",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-198-df7441a2-0-0-chronicler---01---01",
    "name": "Cronista humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-198-df7441a2-0-0-chronicler---01---02",
    "name": "Cronista humano · 2",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-198-e2da9c9f-0-0-volo-geddarm",
    "name": "Cronista humano · 3",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-203-2a8df77f-0-0-swashbuckler-101",
    "name": "Espadachim humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "ladino",
      "bardo",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-203-2a8df77f-0-0-swashbuckler-102",
    "name": "Espadachim humano · 2",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "ladino",
      "bardo",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-203-2a8df77f-0-0-swashbuckler-103",
    "name": "Espadachim humano · 3",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "ladino",
      "bardo",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-203-bc453988-0-0-swashbuckler-101",
    "name": "Espadachim humano · 4",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "ladino",
      "bardo",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-204-0-0-swashbuckler-101",
    "name": "Bardo humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo"
    ]
  },
  {
    "id": "printableheroes-mini-204-0-0-swashbuckler-102",
    "name": "Bardo humano · 2",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo"
    ]
  },
  {
    "id": "printableheroes-mini-204-0-0-swashbuckler-103",
    "name": "Bardo humano · 3",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo"
    ]
  },
  {
    "id": "printableheroes-mini-206-0-0-ho---warlock---0101",
    "name": "Bruxo orc",
    "origin": "orc",
    "appearance": "masculina",
    "styles": [
      "bruxo"
    ]
  },
  {
    "id": "printableheroes-mini-210-0-0-drow---priest---0101",
    "name": "Paladina elfa",
    "origin": "elfo",
    "appearance": "feminina",
    "styles": [
      "paladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-210-0-0-drow---priest---0102",
    "name": "Paladina elfa · 2",
    "origin": "elfo",
    "appearance": "feminina",
    "styles": [
      "paladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-218-0-0-standee-1-image-1",
    "name": "Guardião draconato",
    "origin": "draconato",
    "appearance": "masculina",
    "styles": [
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-219-0-0-standee-1-image-1",
    "name": "Guardião draconato · 2",
    "origin": "draconato",
    "appearance": "masculina",
    "styles": [
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-22-0-0-db_barb_01_02",
    "name": "Paladino draconato",
    "origin": "draconato",
    "appearance": "masculina",
    "styles": [
      "paladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-22-0-0-dwarf_wizard_01_01",
    "name": "Mago anão",
    "origin": "anao",
    "appearance": "masculina",
    "styles": [
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-22-0-0-dwarf_wizard_01_02",
    "name": "Mago anão · 2",
    "origin": "anao",
    "appearance": "masculina",
    "styles": [
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-22-0-0-elfranger0102",
    "name": "Guardião elfo · 5",
    "origin": "elfo",
    "appearance": "masculina",
    "styles": [
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-22-0-0-elfranger0103",
    "name": "Guardião elfo · 6",
    "origin": "elfo",
    "appearance": "masculina",
    "styles": [
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-22-0-0-halfling_rogue_01_02",
    "name": "Ladino pequenino",
    "origin": "halfling",
    "appearance": "masculina",
    "styles": [
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-22-0-0-halfling_rogue_01_03",
    "name": "Ladino pequenino · 2",
    "origin": "halfling",
    "appearance": "masculina",
    "styles": [
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-246-0-0-h---druid---01010",
    "name": "Druida humana",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "druida"
    ]
  },
  {
    "id": "printableheroes-mini-246-0-0-h---druid---0109",
    "name": "Druida humana · 2",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "druida"
    ]
  },
  {
    "id": "printableheroes-mini-248-0-0-tiefling---rogue---0101",
    "name": "Ladina tiferina",
    "origin": "tiefling",
    "appearance": "feminina",
    "styles": [
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-254-0-0-human---noble---0101",
    "name": "Nobre humana",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "bardo",
      "paladino"
    ]
  },
  {
    "id": "printableheroes-mini-254-0-0-human---noble---01014",
    "name": "Nobre humana · 2",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "bardo",
      "paladino"
    ]
  },
  {
    "id": "printableheroes-mini-255-0-0-human---noble---0401",
    "name": "Nobre humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "paladino"
    ]
  },
  {
    "id": "printableheroes-mini-255-0-0-human---noble---0402",
    "name": "Nobre humano · 2",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "paladino"
    ]
  },
  {
    "id": "printableheroes-mini-256-0-0-human---noble---0401",
    "name": "Aventureiro orc · 2",
    "origin": "orc",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-28-0-0-em_01_02",
    "name": "Monge elfo · 5",
    "origin": "elfo",
    "appearance": "masculina",
    "styles": [
      "monge"
    ]
  },
  {
    "id": "printableheroes-mini-28-0-0-elfdruidf0102",
    "name": "Druida elfa · 2",
    "origin": "elfo",
    "appearance": "feminina",
    "styles": [
      "druida"
    ]
  },
  {
    "id": "printableheroes-mini-28-0-0-hw0102",
    "name": "Mago humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-28-0-0-tp_01_02",
    "name": "Paladino tiferino",
    "origin": "tiefling",
    "appearance": "masculina",
    "styles": [
      "paladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-284-0-0-eldritch-knight-0101",
    "name": "Cavaleiro humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro",
      "paladino"
    ]
  },
  {
    "id": "printableheroes-mini-284-0-0-eldritch-knight-0102",
    "name": "Cavaleiro humano · 2",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro",
      "paladino"
    ]
  },
  {
    "id": "printableheroes-mini-285-0-0-eldritch-knight-0101",
    "name": "Pistoleiro humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-285-0-0-eldritch-knight-0102",
    "name": "Pistoleiro humano · 2",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-287-0-0-aasimar-wanderer---0101",
    "name": "Andarilha aasimar",
    "origin": "aasimar",
    "appearance": "feminina",
    "styles": [
      "guardiao",
      "monge"
    ]
  },
  {
    "id": "printableheroes-mini-287-0-0-aasimar-wanderer---0102",
    "name": "Andarilha aasimar · 2",
    "origin": "aasimar",
    "appearance": "feminina",
    "styles": [
      "guardiao",
      "monge"
    ]
  },
  {
    "id": "printableheroes-mini-305-0-0-tiefling---warlock---0201",
    "name": "Bruxa tiferina",
    "origin": "tiefling",
    "appearance": "feminina",
    "styles": [
      "bruxo"
    ]
  },
  {
    "id": "printableheroes-mini-310-0-0-earth-cultist---0101",
    "name": "Cultista humano · 6",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bruxo",
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-mini-310-0-0-earth-cultist---0102",
    "name": "Cultista humano · 7",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bruxo",
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-mini-311-0-0-demon-slayer---0101",
    "name": "Aventureiro elfo · 5",
    "origin": "elfo",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-311-0-0-demon-slayer---0102",
    "name": "Aventureiro elfo · 6",
    "origin": "elfo",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-328-0-0-tiefling---paladin---0201",
    "name": "Paladino tiferino · 2",
    "origin": "tiefling",
    "appearance": "masculina",
    "styles": [
      "paladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-33-0-0-standee-2-image-1",
    "name": "Aventureira humana",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-33-0-0-standee-2-image-2",
    "name": "Aventureira humana · 2",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-330-0-0-tiefling-paladin---03032",
    "name": "Paladina tiferina",
    "origin": "tiefling",
    "appearance": "feminina",
    "styles": [
      "paladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-331-0-0-tiefling-hexblade-01",
    "name": "Bruxo da lâmina tiferino",
    "origin": "tiefling",
    "appearance": "masculina",
    "styles": [
      "bruxo",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-339-0-0-tiefling-monk---01",
    "name": "Monge tiferino",
    "origin": "tiefling",
    "appearance": "masculina",
    "styles": [
      "monge"
    ]
  },
  {
    "id": "printableheroes-mini-34-0-0-standee-1-image-1",
    "name": "Nobre humano · 3",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "paladino"
    ]
  },
  {
    "id": "printableheroes-mini-34-0-0-standee-1-image-2",
    "name": "Nobre humano · 4",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "paladino"
    ]
  },
  {
    "id": "printableheroes-mini-342-0-0-tiefling---noble---0101",
    "name": "Nobre tiferina",
    "origin": "tiefling",
    "appearance": "feminina",
    "styles": [
      "bardo",
      "paladino"
    ]
  },
  {
    "id": "printableheroes-mini-348-0-0-tiefling---noble---0201",
    "name": "Nobre tiferino",
    "origin": "tiefling",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "paladino"
    ]
  },
  {
    "id": "printableheroes-mini-349-0-0-tiefling---townsfolk---01",
    "name": "Aventureira tiferina",
    "origin": "tiefling",
    "appearance": "feminina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-35-0-0-standee-1-image-1",
    "name": "Mercador humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-35-0-0-standee-1-image-2",
    "name": "Mercador humano · 2",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-35-0-0-standee-1-image-3",
    "name": "Mercador humano · 3",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-355-0-0-tiefling---bandit---0101",
    "name": "Bandido tiferino",
    "origin": "tiefling",
    "appearance": "masculina",
    "styles": [
      "ladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-356-0-0-berserker---0101",
    "name": "Berserker humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "barbaro",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-358-0-0-human---tribal---0101",
    "name": "Combatente tribal humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "barbaro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-36-0-0-standee-1-image-1",
    "name": "Mago humano · 2",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-36-0-0-standee-1-image-2",
    "name": "Mago humano · 3",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-364-0-0-db---barbarian---0101",
    "name": "Bárbaro draconato",
    "origin": "draconato",
    "appearance": "masculina",
    "styles": [
      "barbaro"
    ]
  },
  {
    "id": "printableheroes-mini-366-0-0-db---bard---0101",
    "name": "Bardo draconato",
    "origin": "draconato",
    "appearance": "masculina",
    "styles": [
      "bardo"
    ]
  },
  {
    "id": "printableheroes-mini-368-0-0-db---cleric---0101",
    "name": "Clérigo draconato",
    "origin": "draconato",
    "appearance": "masculina",
    "styles": [
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-mini-370-0-0-standee-1-image-1",
    "name": "Paladino draconato · 2",
    "origin": "draconato",
    "appearance": "masculina",
    "styles": [
      "paladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-387-0-0-human---druid---0201",
    "name": "Druida humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "druida"
    ]
  },
  {
    "id": "printableheroes-mini-396-0-0-human---thug---0101",
    "name": "Aventureiro humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-396-0-0-human---thug---0102",
    "name": "Aventureiro humano · 2",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-397-0-0-human---thug---0101",
    "name": "Aventureiro humano · 3",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-397-0-0-human---thug---0102",
    "name": "Aventureiro humano · 4",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-399-0-0-human---bard---0201",
    "name": "Barda humana",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "bardo"
    ]
  },
  {
    "id": "printableheroes-mini-399-0-0-human---bard---0202",
    "name": "Barda humana · 2",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "bardo"
    ]
  },
  {
    "id": "printableheroes-mini-401-0-0-halfling---paladin---0101",
    "name": "Paladina pequenina",
    "origin": "halfling",
    "appearance": "feminina",
    "styles": [
      "paladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-401-0-0-halfling---paladin---0102",
    "name": "Paladina pequenina · 2",
    "origin": "halfling",
    "appearance": "feminina",
    "styles": [
      "paladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-414-0-0-wizard---0401",
    "name": "Mago humano · 4",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-414-0-0-wizard---0402",
    "name": "Mago humano · 5",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-422-0-0-human---apothecary---0101",
    "name": "Herbalista humana",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "druida",
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-mini-422-0-0-human---apothecary---0102",
    "name": "Herbalista humana · 2",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "druida",
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-mini-428-0-0-dwarf---brawler---0101",
    "name": "Lutador anão",
    "origin": "anao",
    "appearance": "masculina",
    "styles": [
      "monge",
      "barbaro",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-428-0-0-dwarf---brawler---0102",
    "name": "Lutador anão · 2",
    "origin": "anao",
    "appearance": "masculina",
    "styles": [
      "monge",
      "barbaro",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-466-0-0-vampire-spawn---0101",
    "name": "Bandido humano · 5",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "ladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-467-0-0-vampire-spawn---0101",
    "name": "Bandido humano · 6",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "ladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-508-0-0-dwarf---apothecary---0101",
    "name": "Herbalista anão",
    "origin": "anao",
    "appearance": "masculina",
    "styles": [
      "druida",
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-mini-508-0-0-dwarf---apothecary---0102",
    "name": "Herbalista anão · 2",
    "origin": "anao",
    "appearance": "masculina",
    "styles": [
      "druida",
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-mini-51-8e11247d-0-0-db_barb_01_01",
    "name": "Paladino draconato · 3",
    "origin": "draconato",
    "appearance": "masculina",
    "styles": [
      "paladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-51-8e11247d-0-0-db_barb_01_02",
    "name": "Ladino draconato",
    "origin": "draconato",
    "appearance": "masculina",
    "styles": [
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-51-8e11247d-0-0-db_barb_01_03",
    "name": "Feiticeiro draconato",
    "origin": "draconato",
    "appearance": "masculina",
    "styles": [
      "feiticeiro"
    ]
  },
  {
    "id": "printableheroes-mini-51-b4e3f389-0-0-db_barb_01_01",
    "name": "Bárbaro draconato · 2",
    "origin": "draconato",
    "appearance": "masculina",
    "styles": [
      "barbaro"
    ]
  },
  {
    "id": "printableheroes-mini-51-b4e3f389-0-0-db_barb_01_02",
    "name": "Bardo draconato · 2",
    "origin": "draconato",
    "appearance": "masculina",
    "styles": [
      "bardo"
    ]
  },
  {
    "id": "printableheroes-mini-51-b4e3f389-0-0-db_barb_01_03",
    "name": "Clérigo draconato · 2",
    "origin": "draconato",
    "appearance": "masculina",
    "styles": [
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-mini-521-0-0-human---guard---0101",
    "name": "Miliciano humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-521-0-0-human---guard---0102",
    "name": "Miliciano humano · 2",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-522-0-0-human---guard---0101",
    "name": "Sentinela humana",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "guerreiro",
      "paladino"
    ]
  },
  {
    "id": "printableheroes-mini-522-0-0-human---guard---0102",
    "name": "Sentinela humana · 2",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "guerreiro",
      "paladino"
    ]
  },
  {
    "id": "printableheroes-mini-524-0-0-human---guard---0101",
    "name": "Miliciano humano · 3",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-524-0-0-human---guard---0102",
    "name": "Miliciano humano · 4",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-524-0-0-human---guard---0103",
    "name": "Miliciano humano · 5",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-525-0-0-human---guard---0101",
    "name": "Miliciano humano · 6",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-525-0-0-human---guard---0102",
    "name": "Miliciano humano · 7",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-526-0-0-human---guard---0101",
    "name": "Miliciana humana",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-526-0-0-human---guard---0102",
    "name": "Miliciana humana · 2",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-526-0-0-human---guard---0103",
    "name": "Miliciana humana · 3",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-527-0-0-human---guard---0101",
    "name": "Miliciana humana · 4",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-527-0-0-human---guard---0102",
    "name": "Miliciana humana · 5",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-535-0-0-human---wizard---0501",
    "name": "Mago humano · 6",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-535-0-0-human---wizard---0502",
    "name": "Mago humano · 7",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-536-0-0-human---wizard---0501",
    "name": "Maga humana",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-536-0-0-human---wizard---0502",
    "name": "Maga humana · 2",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-539-0-0-db---monk---0101",
    "name": "Monge draconato",
    "origin": "draconato",
    "appearance": "masculina",
    "styles": [
      "monge"
    ]
  },
  {
    "id": "printableheroes-mini-540-0-0-db---monk---0101",
    "name": "Bruxo draconato",
    "origin": "draconato",
    "appearance": "masculina",
    "styles": [
      "bruxo"
    ]
  },
  {
    "id": "printableheroes-mini-542-0-0-tiefling---paladin---0101",
    "name": "Paladino tiferino · 3",
    "origin": "tiefling",
    "appearance": "masculina",
    "styles": [
      "paladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-545-0-0-saeth-cromley---0101",
    "name": "Aventureiro humano · 5",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-545-0-0-saeth-cromley---0102",
    "name": "Aventureiro humano · 6",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-545-0-0-saeth-cromley---0103",
    "name": "Aventureiro humano · 7",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-545-0-0-saeth-cromley---0104",
    "name": "Aventureiro humano · 8",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-552-0-0-hm0601",
    "name": "Miliciano humano · 8",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-552-0-0-hm0602",
    "name": "Miliciano humano · 9",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-554-0-0-hm0601",
    "name": "Miliciano humano · 10",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-554-0-0-hm0602",
    "name": "Miliciano humano · 11",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-555-0-0-hm0601",
    "name": "Miliciana humana · 6",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-555-0-0-hm0602",
    "name": "Miliciana humana · 7",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-556-0-0-hm0601",
    "name": "Miliciana humana · 8",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-556-0-0-hm0602",
    "name": "Miliciana humana · 9",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-557-0-0-hm0601",
    "name": "Miliciano humano · 12",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-557-0-0-hm0602",
    "name": "Miliciano humano · 13",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-558-0-0-0101",
    "name": "Batedor humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guardiao",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-558-0-0-0102",
    "name": "Batedor humano · 2",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guardiao",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-559-0-0-0101",
    "name": "Batedora humana",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "guardiao",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-559-0-0-0102",
    "name": "Batedora humana · 2",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "guardiao",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-562-0-0-0101",
    "name": "Batedor humano · 3",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guardiao",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-562-0-0-0102",
    "name": "Batedor humano · 4",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guardiao",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-565-0-0-0101",
    "name": "Batedora humana · 3",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "guardiao",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-565-0-0-0102",
    "name": "Batedora humana · 4",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "guardiao",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-570-0-0-0101",
    "name": "Soldado humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-570-0-0-0102",
    "name": "Soldado humano · 2",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-571-0-0-0101",
    "name": "Soldada humana",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-571-0-0-0102",
    "name": "Soldada humana · 2",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-572-0-0-0101",
    "name": "Soldado humano · 3",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-572-0-0-0102",
    "name": "Soldado humano · 4",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-573-0-0-0101",
    "name": "Soldada humana · 3",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-573-0-0-0102",
    "name": "Soldada humana · 4",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-584-0-0-0101",
    "name": "Druida humano · 2",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "druida"
    ]
  },
  {
    "id": "printableheroes-mini-584-0-0-0102",
    "name": "Druida humano · 3",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "druida"
    ]
  },
  {
    "id": "printableheroes-mini-586-0-0-0101",
    "name": "Artífice humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "mago",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-586-0-0-0102",
    "name": "Artífice humano · 2",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "mago",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-587-0-0-01",
    "name": "Guardião humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-587-0-0-02",
    "name": "Guardião humano · 2",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-588-0-0-01",
    "name": "Guardiã humana",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-588-0-0-02",
    "name": "Guardiã humana · 2",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-589-0-0-sorcerer---0101",
    "name": "Feiticeira orc",
    "origin": "orc",
    "appearance": "feminina",
    "styles": [
      "feiticeiro"
    ]
  },
  {
    "id": "printableheroes-mini-589-0-0-sorcerer---0102",
    "name": "Feiticeira orc · 2",
    "origin": "orc",
    "appearance": "feminina",
    "styles": [
      "feiticeiro"
    ]
  },
  {
    "id": "printableheroes-mini-590-0-0-sorcerer---0101",
    "name": "Maga orc",
    "origin": "orc",
    "appearance": "feminina",
    "styles": [
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-590-0-0-sorcerer---0102",
    "name": "Maga orc · 2",
    "origin": "orc",
    "appearance": "feminina",
    "styles": [
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-591-0-0-sorcerer---0101",
    "name": "Arcanista orc",
    "origin": "orc",
    "appearance": "feminina",
    "styles": [
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-591-0-0-sorcerer---0102",
    "name": "Arcanista orc · 2",
    "origin": "orc",
    "appearance": "feminina",
    "styles": [
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-592-0-0-rogue---0101",
    "name": "Ladino humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-592-0-0-rogue---0102",
    "name": "Ladino humano · 2",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-593-0-0-rogue---0101",
    "name": "Ladina humana",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-593-0-0-rogue---0102",
    "name": "Ladina humana · 2",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-596-0-0-standee-1-image-1",
    "name": "Clériga humana",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-mini-596-0-0-standee-1-image-2",
    "name": "Clériga humana · 2",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-mini-6-0-0-goliath_barbarian_0101",
    "name": "Bárbaro golias",
    "origin": "golias",
    "appearance": "masculina",
    "styles": [
      "barbaro"
    ]
  },
  {
    "id": "printableheroes-mini-607-0-0-standee-1-image-1",
    "name": "Druida humana · 3",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "druida"
    ]
  },
  {
    "id": "printableheroes-mini-607-0-0-standee-1-image-2",
    "name": "Druida humana · 4",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "druida"
    ]
  },
  {
    "id": "printableheroes-mini-608-0-0-standee-1-image-1",
    "name": "Druida humana · 5",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "druida"
    ]
  },
  {
    "id": "printableheroes-mini-608-0-0-standee-1-image-2",
    "name": "Druida humana · 6",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "druida"
    ]
  },
  {
    "id": "printableheroes-mini-615-0-0-standee-1-image-1",
    "name": "Artífice humano · 3",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "mago",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-615-0-0-standee-1-image-2",
    "name": "Artífice humano · 4",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "mago",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-616-0-0-standee-1-image-1",
    "name": "Artífice humano · 5",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "mago",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-616-0-0-standee-1-image-2",
    "name": "Artífice humano · 6",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "mago",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-650-0-0-standee-1-image-1",
    "name": "Bárbaro humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "barbaro"
    ]
  },
  {
    "id": "printableheroes-mini-650-0-0-standee-1-image-2",
    "name": "Bárbaro humano · 2",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "barbaro"
    ]
  },
  {
    "id": "printableheroes-mini-652-0-0-standee-1-image-1",
    "name": "Bárbara humana",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "barbaro"
    ]
  },
  {
    "id": "printableheroes-mini-652-0-0-standee-1-image-2",
    "name": "Bárbara humana · 2",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "barbaro"
    ]
  },
  {
    "id": "printableheroes-mini-653-0-0-standee-1-image-1",
    "name": "Bárbaro humano · 3",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "barbaro"
    ]
  },
  {
    "id": "printableheroes-mini-653-0-0-standee-1-image-2",
    "name": "Bárbaro humano · 4",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "barbaro"
    ]
  },
  {
    "id": "printableheroes-mini-653-0-0-standee-1-image-3",
    "name": "Bárbaro humano · 5",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "barbaro"
    ]
  },
  {
    "id": "printableheroes-mini-653-0-0-standee-1-image-4",
    "name": "Bárbaro humano · 6",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "barbaro"
    ]
  },
  {
    "id": "printableheroes-mini-654-0-0-standee-1-image-1",
    "name": "Bárbara humana · 3",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "barbaro"
    ]
  },
  {
    "id": "printableheroes-mini-654-0-0-standee-1-image-2",
    "name": "Bárbara humana · 4",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "barbaro"
    ]
  },
  {
    "id": "printableheroes-mini-654-0-0-standee-1-image-3",
    "name": "Bárbara humana · 5",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "barbaro"
    ]
  },
  {
    "id": "printableheroes-mini-654-0-0-standee-1-image-4",
    "name": "Bárbara humana · 6",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "barbaro"
    ]
  },
  {
    "id": "printableheroes-mini-681-0-0-standee-1-image-1",
    "name": "Ocultista humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bruxo",
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-681-0-0-standee-1-image-3",
    "name": "Ocultista humano · 2",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bruxo",
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-682-0-0-standee-1-image-1",
    "name": "Ocultista humana",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "bruxo",
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-682-0-0-standee-1-image-3",
    "name": "Ocultista humana · 2",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "bruxo",
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-685-0-0-standee-1-image-1",
    "name": "Ocultista humano · 3",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bruxo",
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-685-0-0-standee-1-image-2",
    "name": "Ocultista humano · 4",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bruxo",
      "mago"
    ]
  },
  {
    "id": "printableheroes-mini-69-0-0-standee-1-image-1",
    "name": "Clériga elfa",
    "origin": "elfo",
    "appearance": "feminina",
    "styles": [
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-mini-69-0-0-standee-1-image-2",
    "name": "Clériga elfa · 2",
    "origin": "elfo",
    "appearance": "feminina",
    "styles": [
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-mini-694-0-0-standee-1-image-1",
    "name": "Exploradora humana",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "guardiao",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-694-0-0-standee-1-image-2",
    "name": "Exploradora humana · 2",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "guardiao",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-696-0-0-standee-1-image-1",
    "name": "Explorador humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guardiao",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-696-0-0-standee-1-image-2",
    "name": "Explorador humano · 2",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guardiao",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-7-0-0-goliath_barbarian_0201",
    "name": "Bárbara golias",
    "origin": "golias",
    "appearance": "feminina",
    "styles": [
      "barbaro"
    ]
  },
  {
    "id": "printableheroes-mini-705-0-0-standee-1-image-1",
    "name": "Herbalista humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "druida",
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-mini-705-0-0-standee-1-image-2",
    "name": "Herbalista humano · 2",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "druida",
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-mini-706-0-0-standee-1-image-1",
    "name": "Herbalista humana · 3",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "druida",
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-mini-706-0-0-standee-1-image-2",
    "name": "Herbalista humana · 4",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "druida",
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-mini-717-0-0-standee-1-image-1",
    "name": "Ladino pequenino · 3",
    "origin": "halfling",
    "appearance": "masculina",
    "styles": [
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-717-0-0-standee-1-image-2",
    "name": "Ladino pequenino · 4",
    "origin": "halfling",
    "appearance": "masculina",
    "styles": [
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-717-0-0-standee-1-image-3",
    "name": "Ladino pequenino · 5",
    "origin": "halfling",
    "appearance": "masculina",
    "styles": [
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-717-0-0-standee-1-image-4",
    "name": "Ladino pequenino · 6",
    "origin": "halfling",
    "appearance": "masculina",
    "styles": [
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-718-0-0-standee-1-image-1",
    "name": "Bardo pequenino",
    "origin": "halfling",
    "appearance": "masculina",
    "styles": [
      "bardo"
    ]
  },
  {
    "id": "printableheroes-mini-718-0-0-standee-1-image-2",
    "name": "Bardo pequenino · 2",
    "origin": "halfling",
    "appearance": "masculina",
    "styles": [
      "bardo"
    ]
  },
  {
    "id": "printableheroes-mini-721-0-0-standee-1-image-1",
    "name": "Cavaleiro humano · 3",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro",
      "paladino"
    ]
  },
  {
    "id": "printableheroes-mini-721-0-0-standee-1-image-2",
    "name": "Cavaleiro humano · 4",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro",
      "paladino"
    ]
  },
  {
    "id": "printableheroes-mini-726-0-0-standee-1-image-1",
    "name": "Necromante humana",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "mago",
      "bruxo"
    ]
  },
  {
    "id": "printableheroes-mini-726-0-0-standee-1-image-2",
    "name": "Necromante humana · 2",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "mago",
      "bruxo"
    ]
  },
  {
    "id": "printableheroes-mini-749-0-0-standee-1-image-1",
    "name": "Bandido humano · 7",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "ladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-749-0-0-standee-1-image-2",
    "name": "Bandido humano · 8",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "ladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-750-0-0-standee-1-image-1",
    "name": "Bandida humana",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "ladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-750-0-0-standee-1-image-2",
    "name": "Bandida humana · 2",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "ladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-751-0-0-standee-1-image-1",
    "name": "Necromante humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "mago",
      "bruxo"
    ]
  },
  {
    "id": "printableheroes-mini-751-0-0-standee-1-image-2",
    "name": "Necromante humano · 2",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "mago",
      "bruxo"
    ]
  },
  {
    "id": "printableheroes-mini-759-0-0-standee-1-image-1",
    "name": "Guerreira elfa",
    "origin": "elfo",
    "appearance": "feminina",
    "styles": [
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-759-0-0-standee-1-image-2",
    "name": "Guerreira elfa · 2",
    "origin": "elfo",
    "appearance": "feminina",
    "styles": [
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-759-0-0-standee-1-image-3",
    "name": "Guerreira elfa · 3",
    "origin": "elfo",
    "appearance": "feminina",
    "styles": [
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-759-0-0-standee-1-image-4",
    "name": "Guerreira elfa · 4",
    "origin": "elfo",
    "appearance": "feminina",
    "styles": [
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-759-0-0-standee-1-image-5",
    "name": "Guerreira elfa · 5",
    "origin": "elfo",
    "appearance": "feminina",
    "styles": [
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-759-0-0-standee-1-image-6",
    "name": "Guerreira elfa · 6",
    "origin": "elfo",
    "appearance": "feminina",
    "styles": [
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-760-0-0-standee-1-image-1",
    "name": "Aventureira elfa",
    "origin": "elfo",
    "appearance": "feminina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-760-0-0-standee-1-image-2",
    "name": "Aventureira elfa · 2",
    "origin": "elfo",
    "appearance": "feminina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-760-0-0-standee-1-image-3",
    "name": "Aventureira elfa · 3",
    "origin": "elfo",
    "appearance": "feminina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-760-0-0-standee-1-image-4",
    "name": "Aventureira elfa · 4",
    "origin": "elfo",
    "appearance": "feminina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-760-0-0-standee-1-image-5",
    "name": "Aventureira elfa · 5",
    "origin": "elfo",
    "appearance": "feminina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-760-0-0-standee-1-image-6",
    "name": "Aventureira elfa · 6",
    "origin": "elfo",
    "appearance": "feminina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-760-0-0-standee-1-image-7",
    "name": "Aventureira elfa · 7",
    "origin": "elfo",
    "appearance": "feminina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-760-0-0-standee-1-image-8",
    "name": "Aventureira elfa · 8",
    "origin": "elfo",
    "appearance": "feminina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-762-0-0-standee-1-image-1",
    "name": "Bárbara orc",
    "origin": "orc",
    "appearance": "feminina",
    "styles": [
      "barbaro"
    ]
  },
  {
    "id": "printableheroes-mini-763-0-0-standee-1-image-1",
    "name": "Bárbaro orc",
    "origin": "orc",
    "appearance": "masculina",
    "styles": [
      "barbaro"
    ]
  },
  {
    "id": "printableheroes-mini-764-0-0-standee-1-image-1",
    "name": "Bárbaro orc · 2",
    "origin": "orc",
    "appearance": "masculina",
    "styles": [
      "barbaro"
    ]
  },
  {
    "id": "printableheroes-mini-768-0-0-standee-1-image-1",
    "name": "Druida humano · 4",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "druida"
    ]
  },
  {
    "id": "printableheroes-mini-769-0-0-standee-1-image-1",
    "name": "Druida humana · 7",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "druida"
    ]
  },
  {
    "id": "printableheroes-mini-785-0-0-standee-1-image-1",
    "name": "Combatente tribal humana",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "barbaro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-785-0-0-standee-1-image-2",
    "name": "Combatente tribal humana · 2",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "barbaro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-788-0-0-standee-1-image-1",
    "name": "Clérigo anão",
    "origin": "anao",
    "appearance": "masculina",
    "styles": [
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-mini-788-0-0-standee-1-image-2",
    "name": "Clérigo anão · 2",
    "origin": "anao",
    "appearance": "masculina",
    "styles": [
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-mini-8-0-0-human_warrior_00_03",
    "name": "Paladino humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "paladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-8-0-0-human_warrior_00_04",
    "name": "Paladino humano · 2",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "paladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-8-0-0-human_warrior_01_02",
    "name": "Paladina humana",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "paladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-8-0-0-human_warrior_01_03",
    "name": "Paladina humana · 2",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "paladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-813-0-0-standee-1-image-1",
    "name": "Artífice gnoma",
    "origin": "gnomo",
    "appearance": "feminina",
    "styles": [
      "mago",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-813-0-0-standee-1-image-2",
    "name": "Artífice gnoma · 2",
    "origin": "gnomo",
    "appearance": "feminina",
    "styles": [
      "mago",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-814-0-0-standee-1-image-1",
    "name": "Artífice gnomo",
    "origin": "gnomo",
    "appearance": "masculina",
    "styles": [
      "mago",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-814-0-0-standee-1-image-2",
    "name": "Artífice gnomo · 2",
    "origin": "gnomo",
    "appearance": "masculina",
    "styles": [
      "mago",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-823-0-0-standee-1-image-1",
    "name": "Aventureiro humano · 9",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-824-0-0-standee-1-image-1",
    "name": "Aventureira humana · 3",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-824-0-0-standee-1-image-2",
    "name": "Aventureira humana · 4",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-827-0-0-standee-1-image-1",
    "name": "Aventureiro humano · 10",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-827-0-0-standee-1-image-2",
    "name": "Aventureiro humano · 11",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-828-0-0-standee-1-image-1",
    "name": "Aventureiro humano · 12",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-828-0-0-standee-1-image-2",
    "name": "Aventureiro humano · 13",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-84-0-0-standee-1-image-1",
    "name": "Cultista humano · 8",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bruxo",
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-mini-84-0-0-standee-1-image-2",
    "name": "Cultista humano · 9",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bruxo",
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-mini-847-0-0-standee-1-image-1",
    "name": "Ferreiro humano",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro",
      "barbaro"
    ]
  },
  {
    "id": "printableheroes-mini-847-0-0-standee-1-image-2",
    "name": "Ferreiro humano · 2",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro",
      "barbaro"
    ]
  },
  {
    "id": "printableheroes-mini-848-0-0-standee-1-image-1",
    "name": "Ferreira humana",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "guerreiro",
      "barbaro"
    ]
  },
  {
    "id": "printableheroes-mini-848-0-0-standee-1-image-2",
    "name": "Ferreira humana · 2",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "guerreiro",
      "barbaro"
    ]
  },
  {
    "id": "printableheroes-mini-865-0-0-standee-1-image-1",
    "name": "Druida gnoma",
    "origin": "gnomo",
    "appearance": "feminina",
    "styles": [
      "druida"
    ]
  },
  {
    "id": "printableheroes-mini-865-0-0-standee-1-image-2",
    "name": "Druida gnoma · 2",
    "origin": "gnomo",
    "appearance": "feminina",
    "styles": [
      "druida"
    ]
  },
  {
    "id": "printableheroes-mini-881-0-0-standee-1-image-1",
    "name": "Guerreira gnoma",
    "origin": "gnomo",
    "appearance": "feminina",
    "styles": [
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-881-0-0-standee-1-image-2",
    "name": "Guerreira gnoma · 2",
    "origin": "gnomo",
    "appearance": "feminina",
    "styles": [
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-mini-89-0-0-gnomedruidf0101",
    "name": "Druida gnomo",
    "origin": "gnomo",
    "appearance": "masculina",
    "styles": [
      "druida"
    ]
  },
  {
    "id": "printableheroes-mini-9-0-0-human_warrior_00_01",
    "name": "Cavaleiro humano · 5",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro",
      "paladino"
    ]
  },
  {
    "id": "printableheroes-mini-9-0-0-human_warrior_00_02",
    "name": "Cavaleiro humano · 6",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "guerreiro",
      "paladino"
    ]
  },
  {
    "id": "printableheroes-mini-90-0-0-standee-1-image-1",
    "name": "Guardião pequenino · 3",
    "origin": "halfling",
    "appearance": "masculina",
    "styles": [
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-90-0-0-standee-1-image-2",
    "name": "Guardião pequenino · 4",
    "origin": "halfling",
    "appearance": "masculina",
    "styles": [
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-949-0-0-standee-1-image-1",
    "name": "Mercadora humana",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-949-0-0-standee-1-image-2",
    "name": "Mercadora humana · 2",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-950-0-0-standee-1-image-1",
    "name": "Mercador humano · 4",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-950-0-0-standee-1-image-2",
    "name": "Mercador humano · 5",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-959-0-0-standee-2-image-1",
    "name": "Aventureiro humano · 14",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-959-0-0-standee-2-image-2",
    "name": "Aventureiro humano · 15",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-960-0-0-standee-2-image-1",
    "name": "Aventureira humana · 5",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-960-0-0-standee-2-image-2",
    "name": "Aventureira humana · 6",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-mini-971-0-0-standee-2-image-1",
    "name": "Miliciano pequenino",
    "origin": "halfling",
    "appearance": "masculina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-971-0-0-standee-2-image-2",
    "name": "Miliciano pequenino · 2",
    "origin": "halfling",
    "appearance": "masculina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-972-0-0-standee-2-image-1",
    "name": "Miliciano pequenino · 3",
    "origin": "halfling",
    "appearance": "masculina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-972-0-0-standee-2-image-2",
    "name": "Miliciano pequenino · 4",
    "origin": "halfling",
    "appearance": "masculina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-973-0-0-standee-2-image-1",
    "name": "Miliciana pequenina",
    "origin": "halfling",
    "appearance": "feminina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-973-0-0-standee-2-image-2",
    "name": "Miliciana pequenina · 2",
    "origin": "halfling",
    "appearance": "feminina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-974-0-0-standee-2-image-1",
    "name": "Miliciana pequenina · 3",
    "origin": "halfling",
    "appearance": "feminina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-mini-974-0-0-standee-2-image-2",
    "name": "Miliciana pequenina · 4",
    "origin": "halfling",
    "appearance": "feminina",
    "styles": [
      "guerreiro",
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-duergar-0-0-duergar_01_01",
    "name": "Aventureiro anão",
    "origin": "anao",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-duergar-0-0-duergar_01_08",
    "name": "Aventureiro anão · 2",
    "origin": "anao",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-duergar-0-0-duergar_j_01_01",
    "name": "Aventureiro anão · 3",
    "origin": "anao",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-duergar-1-0-duergar_l_01_01",
    "name": "Aventureiro anão · 4",
    "origin": "anao",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-duergar-1-0-duergar_l_01_04",
    "name": "Aventureiro anão · 5",
    "origin": "anao",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-duergar-1-0-duergar_l_j_01_01",
    "name": "Aventureiro anão · 6",
    "origin": "anao",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-duergar-ranger-0-0-duergar-ranger---01",
    "name": "Guardião anão",
    "origin": "anao",
    "appearance": "masculina",
    "styles": [
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-duergar-ranger-0-0-duergar-ranger-enlarge-01",
    "name": "Guardião anão · 2",
    "origin": "anao",
    "appearance": "masculina",
    "styles": [
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-elf-ranger-0-0-elfranger0101",
    "name": "Guardião elfo · 7",
    "origin": "elfo",
    "appearance": "masculina",
    "styles": [
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-elf-ranger-0-0-elfranger0102",
    "name": "Guardião elfo · 8",
    "origin": "elfo",
    "appearance": "masculina",
    "styles": [
      "guardiao"
    ]
  },
  {
    "id": "printableheroes-half-elf-cleric-0-0-hecf01_01",
    "name": "Clériga elfa · 3",
    "origin": "elfo",
    "appearance": "feminina",
    "styles": [
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-half-elf-cleric-0-0-hecf01_02",
    "name": "Clériga elfa · 4",
    "origin": "elfo",
    "appearance": "feminina",
    "styles": [
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-human-cultist-0-0-cultist_0101",
    "name": "Cultista humano · 10",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bruxo",
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-human-cultist-0-0-cultist_0102",
    "name": "Cultista humano · 11",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bruxo",
      "clerigo"
    ]
  },
  {
    "id": "printableheroes-human-merchant-0-0-banditam0102",
    "name": "Bandido humano · 9",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "ladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-human-merchant-0-0-banditff01_02",
    "name": "Bandida humana · 3",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "ladino",
      "guerreiro"
    ]
  },
  {
    "id": "printableheroes-human-merchant-0-0-hm_01",
    "name": "Mercador humano · 6",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-human-merchant-0-0-hm_02",
    "name": "Mercador humano · 7",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-human-townsfolk-0-0-htf_01_01",
    "name": "Aventureira humana · 7",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-human-townsfolk-0-0-htf_01_02",
    "name": "Aventureira humana · 8",
    "origin": "humano",
    "appearance": "feminina",
    "styles": [
      "bardo",
      "ladino"
    ]
  },
  {
    "id": "printableheroes-human-wizard-0-0-hw0101",
    "name": "Mago humano · 8",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "mago"
    ]
  },
  {
    "id": "printableheroes-human-wizard-0-0-hw0102",
    "name": "Mago humano · 9",
    "origin": "humano",
    "appearance": "masculina",
    "styles": [
      "mago"
    ]
  }
];
